services:
  app:
    build:
      context: .
      dockerfile: /todo-frontend/dev.Dockerfile
    container_name: todo-front-dev
    ports:
      - "5173:5173"
    volumes:
      - ./todo-frontend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - VITE_BACKEND_URL=http://localhost:5000/
    command: sh -lc "npm ci && npm run dev -- --host"

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - app
