services:
  # Backernd services
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./todo-backend/mongo_data:/data/db

  redis:
    image: redis
    command: [ 'redis-server', '--appendonly', 'yes' ]
    volumes:
      - ./todo-backend/redis_data:/data

  backend:
    build:
      context: .
      dockerfile: ./todo-backend/dev.Dockerfile
    container_name: todo-backend-dev
    environment:
      MONGO_URL: mongodb://the_username:the_password@mongo:27017/the_database?authSource=the_database
      REDIS_URL: redis://redis:6379
    depends_on:
      - mongo
      - redis

  # Frontend and reverse proxy services
  app:
    build:
      context: .
      dockerfile: /todo-frontend/dev.Dockerfile
    container_name: todo-front-dev
    volumes:
      - ./todo-frontend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - VITE_BACKEND_URL=/api/
    command: sh -lc "npm ci && npm run dev -- --host"

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - app
      - backend
